export const REQUEST_PROCESS_LOCAL = 'GIPHY/REQUEST_PROCESS_LOCAL';

export const REQUEST_SEARCH_GIPHY = 'GIPHY/REQUEST_SEARCH_GIPHY';
export const REQUEST_SEARCH_GIPHY_SUCCESS = 'GIPHY/REQUEST_SEARCH_GIPHY_SUCCESS';
export const REQUEST_SEARCH_GIPHY_FAIL = 'GIPHY/REQUEST_SEARCH_GIPHY_FAIL';

export const REQUEST_INSERT_FAVOURITE = 'GIPHY/REQUEST_INSERT_FAVOURITE';
export const REQUEST_INSERT_FAVOURITE_SUCCESS = 'GIPHY/REQUEST_INSERT_FAVOURITE_SUCCESS';
export const REQUEST_INSERT_FAVOURITE_FAIL = 'GIPHY/REQUEST_INSERT_FAVOURITE_FAIL';

export const REQUEST_ALL_FAVOURITE = 'GIPHY/REQUEST_ALL_FAVOURITE';
export const REQUEST_ALL_FAVOURITE_SUCCESS = 'GIPHY/REQUEST_ALL_FAVOURITE_SUCCESS';
export const REQUEST_ALL_FAVOURITE_FAIL = 'GIPHY/REQUEST_ALL_FAVOURITE_FAIL';

export const REQUEST_MERGE_FAVOURITE = 'GIPHY/REQUEST_MERGE_FAVOURITE';
